const seedData = {
  gamedays: [
    {
      giornata: 1,
      matches: [
        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Parma",
          team2: "Fiorentina",
          pron: "",
          results: "1-1",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Empoli",
          team2: "Monza",
          pron: "",
          results: "0-0",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Milan",
          team2: "Torino",
          pron: "",
          results: "2-2",
        },

        {
          numero: 5,
          day: "dom",
          time: "18:30",
          team1: "Bologna",
          team2: "Udinese",
          pron: "",
          results: "1-1",
        },
        {
          numero: 6,
          day: "dom",
          time: "18:30",
          team1: "Verona",
          team2: "Napoli",
          pron: "",
          results: "3-0",
        },
        {
          numero: 7,
          day: "dom",
          time: "20:45",
          team1: "Cagliari",
          team2: "Roma",
          pron: "",
          results: "0-0",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Lazio",
          team2: "Venezia",
          pron: "",
          results: "3-1",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:30",
          team1: "Lecce",
          team2: "Atalanta",
          pron: "",
          results: "0-4",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Juve",
          team2: "Como",
          pron: "",
          results: "3-0",
        },
      ],
    },
    {
      giornata: 2,
      matches: [
        {
          numero: 1,
          day: "sab",
          time: "18:30",
          team1: "Parma",
          team2: "Milan",
          pron: "",
          results: "2-1",
        },
        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Udinese",
          team2: "Lazio",
          pron: "",
          results: "2-1",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Inter",
          team2: "Lecce",
          pron: "",
          results: "2-0",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Monza",
          team2: "Genoa",
          pron: "",
          results: "0-1",
        },

        {
          numero: 5,
          day: "dom",
          time: "18:30",
          team1: "Fiorentina",
          team2: "Venezia",
          pron: "",
          results: "0-0",
        },
        {
          numero: 6,
          day: "dom",
          time: "18:30",
          team1: "Torino",
          team2: "Atalanta",
          pron: "",
          results: "2-1",
        },
        {
          numero: 7,
          day: "dom",
          time: "20:45",
          team1: "Napoli",
          team2: "Bologna",
          pron: "",
          results: "3-0",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Roma",
          team2: "Empoli",
          pron: "",
          results: "1-2",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:30",
          team1: "Cagliari",
          team2: "Como",
          pron: "",
          results: "1-1",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Verona",
          team2: "Juve",
          pron: "",
          results: "0-3",
        },
      ],
    },
    {
      giornata: 3,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Venezia",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 2,
          day: "ven",
          time: "20:45",
          team1: "Inter",
          team2: "Atalanta",
          pron: "",
          results: "",
        },

        {
          numero: 3,
          day: "sab",
          time: "18:30",
          team1: "Bologna",
          team2: "Empoli",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "18:30",
          team1: "Lecce",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Lazio",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "sab",
          time: "20:45",
          team1: "Napoli",
          team2: "Parma",
          pron: "",
          results: "",
        },

        {
          numero: 7,
          day: "dom",
          time: "18:30",
          team1: "Fiorentina",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:30",
          team1: "Genoa",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Juve",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "dom",
          time: "20:45",
          team1: "Udinese",
          team2: "Como",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 4,
      matches: [
        {
          numero: 1,
          day: "sab",
          time: "18:30",
          team1: "Atalanta",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Cagliari",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Como",
          team2: "Bologna",
          pron: "",
          results: "",
        },

        {
          numero: 4,
          day: "dom",
          time: "12:30",
          team1: "Empoli",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "dom",
          time: "15:00",
          team1: "Genoa",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Lazio",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Milan",
          team2: "Venezia",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Monza",
          team2: "Inter",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Parma",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Torino",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 5,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Atalanta",
          team2: "Como",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "ven",
          time: "18:30",
          team1: "Cagliari",
          team2: "Empoli",
          pron: "1",
          results: "",
        },

        {
          numero: 3,
          day: "sab",
          time: "12:30",
          team1: "Fiorentina",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Verona",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Inter",
          team2: "Milan",
          pron: "",
          results: "",
        },

        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Juve",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Lecce",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Monza",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "18:00",
          team1: "Roma",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "dom",
          time: "20:45",
          team1: "Venezia",
          team2: "Genoa",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 6,
      matches: [
        {
          numero: 1,
          day: "mar",
          time: "18:30",
          team1: "Bologna",
          team2: "Atalanta",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "mer",
          time: "12:30",
          team1: "Como",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "mer",
          time: "15:00",
          team1: "Empoli",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "mer",
          time: "15:00",
          team1: "Genoa",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "mer",
          time: "18:30",
          team1: "Milan",
          team2: "Lecce",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "mer",
          time: "20:45",
          team1: "Napoli",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 7,
          day: "mer",
          time: "20:45",
          team1: "Parma",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },

        {
          numero: 8,
          day: "gio",
          time: "18:00",
          team1: "Roma",
          team2: "Venezia",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "gio",
          time: "18:00",
          team1: "Torino",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "gio",
          time: "20:45",
          team1: "Udinese",
          team2: "Inter",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 7,
      matches: [
        {
          numero: 1,
          day: "sab",
          time: "15:00",
          team1: "Atalanta",
          team2: "Genoa",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "sab",
          time: "18:00",
          team1: "Bologna",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Fiorentina",
          team2: "Milan",
          pron: "",
          results: "",
        },

        {
          numero: 4,
          day: "dom",
          time: "12:30",
          team1: "Verona",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
        {
          numero: 5,
          day: "dom",
          time: "15:00",
          team1: "Inter",
          team2: "Torino",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "18:00",
          team1: "Juve",
          team2: "Cagliari",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "20:30",
          team1: "Lazio",
          team2: "Empoli",
          pron: "1",
          results: "",
        },

        {
          numero: 8,
          day: "lun",
          time: "15:00",
          team1: "Monza",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Napoli",
          team2: "Como",
          pron: "1",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Udinese",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 8,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Cagliari",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 2,
          day: "ven",
          time: "18:30",
          team1: "Como",
          team2: "Parma",
          pron: "",
          results: "",
        },

        {
          numero: 3,
          day: "sab",
          time: "12:30",
          team1: "Empoli",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Genoa",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Verona",
          team2: "Monza",
          pron: "1",
          results: "",
        },

        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Juve",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Lecce",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Milan",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "18:00",
          team1: "Roma",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "dom",
          time: "20:45",
          team1: "Venezia",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 9,
      matches: [
        {
          numero: 1,
          day: "sab",
          time: "18:30",
          team1: "Atalanta",
          team2: "Verona",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Bologna",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Fiorentina",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Inter",
          team2: "Juve",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Lazio",
          team2: "Genoa",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Napoli",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Parma",
          team2: "Empoli",
          pron: "1",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Torino",
          team2: "Como",
          pron: "1",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Udinese",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 10,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Atalanta",
          team2: "Monza",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Cagliari",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Como",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Empoli",
          team2: "Inter",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Genoa",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Juve",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Lecce",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Milan",
          team2: "Napoli",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Roma",
          team2: "Torino",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Udinese",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 11,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Bologna",
          team2: "Lecce",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Empoli",
          team2: "Como",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Verona",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Inter",
          team2: "Venezia",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Lazio",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Napoli",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Parma",
          team2: "Genoa",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Torino",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Udinese",
          team2: "Juve",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 12,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Atalanta",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "ven",
          time: "18:30",
          team1: "Cagliari",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "ven",
          time: "20:45",
          team1: "Fiorentina",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "ven",
          time: "20:45",
          team1: "Genoa",
          team2: "Como",
          pron: "1",
          results: "",
        },

        {
          numero: 5,
          day: "sab",
          time: "12:30",
          team1: "Inter",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "sab",
          time: "15:00",
          team1: "Juve",
          team2: "Torino",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "sab",
          time: "15:00",
          team1: "Lecce",
          team2: "Empoli",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "sab",
          time: "18:00",
          team1: "Monza",
          team2: "Lazio",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "dom",
          time: "18:00",
          team1: "Roma",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "dom",
          time: "20:45",
          team1: "Venezia",
          team2: "Parma",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 13,
      matches: [
        {
          numero: 1,
          day: "sab",
          time: "18:30",
          team1: "Como",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Empoli",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Genoa",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },

        {
          numero: 4,
          day: "dom",
          time: "12:30",
          team1: "Verona",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "dom",
          time: "15:00",
          team1: "Lazio",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Milan",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Napoli",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Parma",
          team2: "Atalanta",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Torino",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 14,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Bologna",
          team2: "Venezia",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Cagliari",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Como",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Fiorentina",
          team2: "Inter",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Lecce",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Milan",
          team2: "Empoli",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Parma",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Roma",
          team2: "Atalanta",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Torino",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Udinese",
          team2: "Genoa",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 15,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Atalanta",
          team2: "Milan",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Fiorentina",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Genoa",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Verona",
          team2: "Empoli",
          pron: "1",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Inter",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Juve",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Napoli",
          team2: "Lazio",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Roma",
          team2: "Lecce",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Como",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 16,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Bologna",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "18:30",
          team1: "Cagliari",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Como",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Empoli",
          team2: "Torino",
          pron: "1",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Juve",
          team2: "Venezia",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Lazio",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Lecce",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Milan",
          team2: "Genoa",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "dom",
          time: "18:00",
          team1: "Parma",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Udinese",
          team2: "Napoli",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 17,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Atalanta",
          team2: "Empoli",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "ven",
          time: "18:30",
          team1: "Fiorentina",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "ven",
          time: "20:45",
          team1: "Genoa",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "ven",
          time: "20:45",
          team1: "Verona",
          team2: "Milan",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "sab",
          time: "12:30",
          team1: "Inter",
          team2: "Como",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "sab",
          time: "15:00",
          team1: "Lecce",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "sab",
          time: "15:00",
          team1: "Monza",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "sab",
          time: "18:00",
          team1: "Roma",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "sab",
          time: "18:00",
          team1: "Torino",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "sab",
          time: "20:45",
          team1: "Venezia",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 18,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Bologna",
          team2: "Verona",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "ven",
          time: "18:30",
          team1: "Cagliari",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "ven",
          time: "20:45",
          team1: "Como",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "ven",
          time: "20:45",
          team1: "Empoli",
          team2: "Genoa",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "sab",
          time: "12:30",
          team1: "Juve",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "sab",
          time: "15:00",
          team1: "Lazio",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "sab",
          time: "15:00",
          team1: "Milan",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "sab",
          time: "18:00",
          team1: "Napoli",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
        {
          numero: 9,
          day: "sab",
          time: "18:00",
          team1: "Parma",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 10,
          day: "sab",
          time: "20:45",
          team1: "Udinese",
          team2: "Torino",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 19,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Atalanta",
          team2: "Juve",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "12:30",
          team1: "Como",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "15:00",
          team1: "Fiorentina",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "18:00",
          team1: "Verona",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Inter",
          team2: "Bologna",
          pron: "",
          results: "",
        },

        {
          numero: 6,
          day: "dom",
          time: "12:30",
          team1: "Lecce",
          team2: "Genoa",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "15:00",
          team1: "Roma",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "18:00",
          team1: "Torino",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "dom",
          time: "20:45",
          team1: "Venezia",
          team2: "Empoli",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 20,
      matches: [
        {
          numero: 1,
          day: "sab",
          time: "15:00",
          team1: "Bologna",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Empoli",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Genoa",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Lazio",
          team2: "Como",
          pron: "1",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Milan",
          team2: "Cagliari",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Napoli",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Torino",
          team2: "Juve",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "20:45",
          team1: "Udinese",
          team2: "Atalanta",
          pron: "",
          results: "",
        },

        {
          numero: 10,
          day: "mar",
          time: "20:45",
          team1: "Venezia",
          team2: "Inter",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 21,
      matches: [
        {
          numero: 1,
          day: "sab",
          time: "18:00",
          team1: "Atalanta",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "sab",
          time: "20:45",
          team1: "Bologna",
          team2: "Monza",
          pron: "",
          results: "",
        },

        {
          numero: 3,
          day: "dom",
          time: "12:30",
          team1: "Cagliari",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "dom",
          time: "15:00",
          team1: "Como",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "dom",
          time: "18:00",
          team1: "Fiorentina",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "20:45",
          team1: "Verona",
          team2: "Lazio",
          pron: "",
          results: "",
        },

        {
          numero: 7,
          day: "lun",
          time: "19:00",
          team1: "Inter",
          team2: "Empoli",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "lun",
          time: "18:00",
          team1: "Juve",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "lun",
          time: "20:45",
          team1: "Parma",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Roma",
          team2: "Genoa",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 22,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Como",
          team2: "Atalanta",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Empoli",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Genoa",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Lazio",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Lecce",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Milan",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Napoli",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Torino",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Udinese",
          team2: "Roma",
          pron: "",
          results: "",
        },

        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Verona",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 23,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Atalanta",
          team2: "Torino",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Bologna",
          team2: "Como",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "15:00",
          team1: "Cagliari",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "18:00",
          team1: "Fiorentina",
          team2: "Genoa",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Juve",
          team2: "Empoli",
          pron: "",
          results: "",
        },

        {
          numero: 6,
          day: "dom",
          time: "12:30",
          team1: "Milan",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Parma",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Roma",
          team2: "Napoli",
          pron: "",
          results: "",
        },

        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Udinese",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 24,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Cagliari",
          team2: "Parma",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Como",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Empoli",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Verona",
          team2: "Atalanta",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Inter",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Lazio",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Lecce",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Napoli",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Torino",
          team2: "Genoa",
          pron: "",
          results: "",
        },

        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Roma",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 25,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "19:00",
          team1: "Atalanta",
          team2: "Cagliari",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "ven",
          time: "21:00",
          team1: "Bologna",
          team2: "Torino",
          pron: "",
          results: "",
        },

        {
          numero: 3,
          day: "sab",
          time: "15:00",
          team1: "Fiorentina",
          team2: "Como",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "18:00",
          team1: "Genoa",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Juve",
          team2: "Inter",
          pron: "",
          results: "",
        },

        {
          numero: 6,
          day: "dom",
          time: "12:30",
          team1: "Lazio",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Milan",
          team2: "Verona",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "18:00",
          team1: "Parma",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "dom",
          time: "20:45",
          team1: "Udinese",
          team2: "Empoli",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 26,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Cagliari",
          team2: "Juve",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Como",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Empoli",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Verona",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Inter",
          team2: "Genoa",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Lecce",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Parma",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Roma",
          team2: "Monza",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Torino",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Lazio",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 27,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Atalanta",
          team2: "Venezia",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Bologna",
          team2: "Cagliari",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Fiorentina",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Genoa",
          team2: "Empoli",
          pron: "1",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Juve",
          team2: "Verona",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Milan",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Napoli",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Roma",
          team2: "Como",
          pron: "",
          results: "",
        },

        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Udinese",
          team2: "Parma",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 28,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Cagliari",
          team2: "Genoa",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Como",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "15:00",
          team1: "Empoli",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "18:00",
          team1: "Verona",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Inter",
          team2: "Monza",
          pron: "",
          results: "",
        },

        {
          numero: 6,
          day: "dom",
          time: "12:30",
          team1: "Juve",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Lazio",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Lecce",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Napoli",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },

        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Parma",
          team2: "Torino",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 29,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Atalanta",
          team2: "Inter",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Bologna",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "15:00",
          team1: "Fiorentina",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "18:00",
          team1: "Genoa",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Milan",
          team2: "Como",
          pron: "",
          results: "",
        },

        {
          numero: 6,
          day: "dom",
          time: "12:30",
          team1: "Monza",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Roma",
          team2: "Cagliari",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Torino",
          team2: "Empoli",
          pron: "1",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "18:00",
          team1: "Udinese",
          team2: "Verona",
          pron: "1",
          results: "",
        },
        {
          numero: 10,
          day: "dom",
          time: "20:45",
          team1: "Venezia",
          team2: "Napoli",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 30,
      matches: [
        {
          numero: 1,
          day: "sab",
          time: "12:30",
          team1: "Cagliari",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Como",
          team2: "Empoli",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "15:00",
          team1: "Fiorentina",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "18:00",
          team1: "Verona",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "sab",
          time: "20:45",
          team1: "Inter",
          team2: "Udinese",
          pron: "",
          results: "",
        },

        {
          numero: 6,
          day: "lun",
          time: "12:30",
          team1: "Juve",
          team2: "Genoa",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "lun",
          time: "15:00",
          team1: "Lazio",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "lun",
          time: "15:00",
          team1: "Lecce",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Napoli",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Bologna",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 31,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Atalanta",
          team2: "Lazio",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Bologna",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Empoli",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Genoa",
          team2: "Udinese",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Lecce",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Milan",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Monza",
          team2: "Como",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Parma",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Roma",
          team2: "Juve",
          pron: "",
          results: "",
        },

        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Torino",
          team2: "Verona",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 32,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Atalanta",
          team2: "Bologna",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Como",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Fiorentina",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Verona",
          team2: "Genoa",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Inter",
          team2: "Cagliari",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Juve",
          team2: "Lecce",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Lazio",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Napoli",
          team2: "Empoli",
          pron: "1",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:30",
          team1: "Udinese",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Monza",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 33,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "18:30",
          team1: "Bologna",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 2,
          day: "ven",
          time: "20:45",
          team1: "Cagliari",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },

        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Empoli",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Genoa",
          team2: "Lazio",
          pron: "",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Lecce",
          team2: "Como",
          pron: "1",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Milan",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Monza",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Parma",
          team2: "Juve",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:30",
          team1: "Roma",
          team2: "Verona",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Torino",
          team2: "Udinese",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 34,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Atalanta",
          team2: "Lecce",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "15:00",
          team1: "Como",
          team2: "Genoa",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Fiorentina",
          team2: "Empoli",
          pron: "1",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Verona",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "12:30",
          team1: "Inter",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Juve",
          team2: "Monza",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "15:00",
          team1: "Lazio",
          team2: "Parma",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "18:00",
          team1: "Napoli",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Udinese",
          team2: "Bologna",
          pron: "",
          results: "",
        },

        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Milan",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 35,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Bologna",
          team2: "Juve",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "18:00",
          team1: "Cagliari",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Empoli",
          team2: "Lazio",
          pron: "",
          results: "",
        },

        {
          numero: 4,
          day: "dom",
          time: "12:30",
          team1: "Genoa",
          team2: "Milan",
          pron: "",
          results: "",
        },
        {
          numero: 5,
          day: "dom",
          time: "15:00",
          team1: "Inter",
          team2: "Verona",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Lecce",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Monza",
          team2: "Atalanta",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Parma",
          team2: "Como",
          pron: "1",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Roma",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Torino",
          team2: "Venezia",
          pron: "1",
          results: "",
        },
      ],
    },
    {
      giornata: 36,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Atalanta",
          team2: "Roma",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "18:00",
          team1: "Como",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Empoli",
          team2: "Parma",
          pron: "",
          results: "",
        },

        {
          numero: 4,
          day: "dom",
          time: "12:30",
          team1: "Verona",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 5,
          day: "dom",
          time: "15:00",
          team1: "Lazio",
          team2: "Juve",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Milan",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Napoli",
          team2: "Genoa",
          pron: "",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Torino",
          team2: "Inter",
          pron: "",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:00",
          team1: "Udinese",
          team2: "Monza",
          pron: "1",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Venezia",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 37,
      matches: [
        {
          numero: 1,
          day: "ven",
          time: "20:45",
          team1: "Cagliari",
          team2: "Venezia",
          pron: "1",
          results: "",
        },

        {
          numero: 2,
          day: "sab",
          time: "18:00",
          team1: "Fiorentina",
          team2: "Bologna",
          pron: "",
          results: "",
        },
        {
          numero: 3,
          day: "sab",
          time: "20:45",
          team1: "Genoa",
          team2: "Atalanta",
          pron: "",
          results: "",
        },

        {
          numero: 4,
          day: "dom",
          time: "12:30",
          team1: "Verona",
          team2: "Como",
          pron: "1",
          results: "",
        },
        {
          numero: 5,
          day: "dom",
          time: "15:00",
          team1: "Inter",
          team2: "Lazio",
          pron: "",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "15:00",
          team1: "Juve",
          team2: "Udinese",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "18:00",
          team1: "Lecce",
          team2: "Torino",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Monza",
          team2: "Empoli",
          pron: "1",
          results: "",
        },

        {
          numero: 9,
          day: "lun",
          time: "18:30",
          team1: "Parma",
          team2: "Napoli",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "lun",
          time: "20:45",
          team1: "Roma",
          team2: "Milan",
          pron: "",
          results: "",
        },
      ],
    },
    {
      giornata: 38,
      matches: [
        {
          numero: 1,
          day: "gio",
          time: "20:45",
          team1: "Atalanta",
          team2: "Parma",
          pron: "",
          results: "",
        },

        {
          numero: 2,
          day: "ven",
          time: "20:45",
          team1: "Bologna",
          team2: "Genoa",
          pron: "",
          results: "",
        },

        {
          numero: 3,
          day: "sab",
          time: "18:00",
          team1: "Como",
          team2: "Inter",
          pron: "",
          results: "",
        },
        {
          numero: 4,
          day: "sab",
          time: "20:45",
          team1: "Empoli",
          team2: "Verona",
          pron: "1",
          results: "",
        },

        {
          numero: 5,
          day: "dom",
          time: "18:00",
          team1: "Lazio",
          team2: "Lecce",
          pron: "1",
          results: "",
        },
        {
          numero: 6,
          day: "dom",
          time: "18:00",
          team1: "Milan",
          team2: "Monza",
          pron: "",
          results: "",
        },
        {
          numero: 7,
          day: "dom",
          time: "20:45",
          team1: "Napoli",
          team2: "Cagliari",
          pron: "1",
          results: "",
        },
        {
          numero: 8,
          day: "dom",
          time: "20:45",
          team1: "Torino",
          team2: "Roma",
          pron: "",
          results: "",
        },
        {
          numero: 9,
          day: "dom",
          time: "20:45",
          team1: "Udinese",
          team2: "Fiorentina",
          pron: "",
          results: "",
        },
        {
          numero: 10,
          day: "dom",
          time: "20:45",
          team1: "Venezia",
          team2: "Juve",
          pron: "",
          results: "",
        },
      ],
    },
  ],
};
module.exports = seedData;
